### PR TITLE
Code improvement in Edi.Documents project

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
1. Removed redundant attached property setter.
2. Removed redundant resource.
3. Removed redundant field initializer.
4. Used expression bodied syntax.
5. Sort modifiers.
6. Removed redundant initializer.
7. Removed not accessed global variable.
8. Used null propagation.
9. Commented unused methods. 
10. Removed redundant `ToString() `call.
11. Method return value is never used.

### CODE REVIEW

**Comment by Dirkster99** [comment]
There was a problem in this pull request which I fixed here:
https://github.com/Dirkster99/Edi/commit/e84cf10d26af166b110e20aae1dfee63574af734

It looks like you removed 2 namespace using statements too many - you also pulled the code from Restyle_1 and created the pulls request against the master :-( which lead me to apply it in the master since it looked OK - How about if we create a branch *CodeImprovement* based on current master and I give you access to the repository - this way you could play with the branch and we can regularly merge from the branch into master when you do a pull request just like this one

- I think this would make it easier to stay in sync we could create a new branch every for each project improvement eg. Util, Documents, ...etc...

**Comment by Dirkster99** [comment]
Here is the new branch from current master:
https://github.com/Dirkster99/Edi/tree/CodeImprovement

**Comment by ShreyasJejurkar** [comment]
Ohhh, Sorry my bad. I mistakenly created pull request against the master branch. I forgot to change the branch to Restyle_1 while creating PR.

**Comment by ShreyasJejurkar** [comment]
Ok, I just cloned the CodeImprovement branch to my machine, And in future, I will create PR against it. If it seems OK to you then merge it into the main branch. Is that OK?

**Comment by ShreyasJejurkar** [comment]
Just wanted to confirm that should I create PR against CodeImprovement branch or push directly to that branch as I have now access to it?

**Comment by Dirkster99** [comment]
Yes, I thought its easier if you commit to the branch new CodeImprovement  directly - you can then use a PR to merge to the master. This way we can always review the current state in the branch and seperate it from the state of the master before and after merging...

For later Code Improvements Steps
...as I wrote above, you can create a branch per project for later code improvements. I usually use GitHub desktop and/or VS to go on to the master - fetch it - create a new branch e.g.: FilesCodeImprovement and commit to it.

You can even create a branch when you work on master by accident but really want to commit - so you can even create a branch on a commit base (but this more of a fallback then a plan-full structured approach...)

**Comment by ShreyasJejurkar** [comment]
Ok. From now onwards am going to push changes to CodeImprovement branch directly. And after some days will create PR against master branch. You also keep eye on changes that I am doing on CodeImprovement branch, if you any suggestion then please let me know. We will work together to isolate it further.

**Comment by ShreyasJejurkar** [comment]
Hey, I need some help with git! 
How can I push changes to CodeImprovements branch directly? I checkout branch from VS to origin/CodeImprovements but when I push changes to remote with git push command, on GitHub its want me to create the new pull request for it to merge to CodeImprovement. But it's not directly pushing those commits to that branch which I wanted.

**Comment by Dirkster99** [comment]
Not sure whats going on. The test PR looks like you are still working from your own repository:

https://github.com/Dirkster99/Edi/pull/40
Dirkster99:CodeImprovement from **MCCshreyas**:CodeImprovement

Maybe you need to check out the Dirkster99/Edi repository and then get on to the CodeImprovement branch. Its probably best if you try to do a completely new clone from:
https://github.com/Dirkster99/Edi

(I would just use clone in GitHub desktop as it usually gets you there without much fuse - thean use VS when you know what folder to use).

What do you get when you do that?

**Comment by Dirkster99** [comment]
Hi Shreyas, are you able to clone from Dirkster99 and commit to the CodeImprovement branch? If not we should a short call via Skype I am sure its not a big issue.

I've send you an email (some time ago) to your address here at GitHub but got no response. Did you get my Email?

Thanks Dirk

**Comment by ShreyasJejurkar** [comment]
screenshot 12

Am getting permission denied while pushing the changes to the branch.

**Comment by ShreyasJejurkar** [comment]
Sorry for late reply. I was quite busy for some last days.

**Comment by Dirkster99** [comment]
The late reply is no problem - tale your time - its just od if there is no reply at all. As I said before, it looks like you are still in your own repository **https://github.com/MCCshreyas/Edi** trying to commit from there into dirkster99. The setting on GitHub is realy simple - I can only invite someone - there is no further setting - so I'd be very surprissed if the problem is on the GutHub side:
githubscreenshot

I know from your blog that you like the command line, but could you please give this a try?
1) Download and install GitHub Desktop: https://desktop.github.com/
2) Goto this repository: https://github.com/Dirkster99/Edi
3) Click the Green **Clone or Download** drop down button and select **Open in Desktop** (or **Open in Visual Studio** if you do not like installing GitHub desktop)
4) Follow the workflow for cloning the repository to your local file system

**Open the project in its new location** in VS and Goto Team Explorer (TW)>Branches (Button)
You should see the CodeImprovement branch and double clicking on it should change its display to **bold** (you are now on the CodeImprovement branch). You can now make a simple change, e.g. add a comment and commit to the branch directly.
vs

Could you please try this workflow - it takes only minutes. Does it work for you? If not, where exactly do you get stuck?

**Comment by ShreyasJejurkar** [comment]
screenshot 14

This is what I get when I followed your steps. 
I think there is a problem in the invitation. Can you please resend me the invite link here itself in your next reply?

**Comment by Dirkster99** [comment]
Here is the link copied from the web front-end at:
https://github.com/Dirkster99/Edi/invitations

**Comment by Dirkster99** [comment]
Hi, I asked the GitHub Support team and they told me that you have to accept the invitation before being able to actually write to the repo.

If that does not work you should get directly in touch with them:
https://github.com/contact

They are usually helpful and quit quick with their suggestions and have helped me a few times too :-)

**Comment by ShreyasJejurkar** [comment]
Am so sorry. I mistakenly deleted the CodeImprovement branch which was created by you. But now I recreated it from current master. And now I am directly able to push code to that branch without creating a separate PR for each of my improvement. Is that OK with you?

**Comment by Dirkster99** [comment]
No problem - you can create, drop, and recreate the CodeImprovement Branch at your own will :-) but please let me know when you want to merge into the master via a PR - I think we should then go on a project by project base - doing this will keep us both in the loop and I can see earily enough when you include something that should not be done in this way...

Normally, I am also using branches and PRs for my own reference and I will do it in the future again :-) - since memory does not seem to be a problem on GitHub we should keep branches around for some time to make sure all changes have been tested and worked out OK in the end. So, its probably best to do branches like CodeImprovement, CodeImprovement_1, CodeImprovement_3 ... in the future.

**Comment by ShreyasJejurkar** [comment]
Yeah. We will go project by project and making improvements in existing code base.
Yesterday I did some code fixes on Edi.SimpleControls project which is very small project. Can you please check out those improvements there? Are that acceptable for you? Or do you have any further suggestions for me? I think we should now contact privately to each other for further discussion and improvements to words the project!

**Pull request merged**
