### PR TITLE
Code improvement - Edi Util 

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**
1. Used ternary operator instead of if and else block for simple condition.
2. Removed redundant `this `qualifier.
3. Converted auto-property to read only.
4. Removed one redundant case block.
5. Used expression body syntax.
6. Used `nameof `expression.
7. Removed one unreachable code .
8. Removed redundant type specification.
9. Used inline `out `variable declaration.

### CODE REVIEW

**Comment by Dirkster99** [comment]
Thanks your suggestions look great and this might help making things more consistent.

I just realized that I am currently working on the **ReStyle_1** branch and will have to merge this into the ReStyle_1 branch as well - which happens to be easy now - but would you be able to request a pull request against the **Restyle_1** branch for the next project? This way could both commit into that branch and finish it off.

Don't worry about a project on the **Restyle_1** branch if its not on the master - I only added some projects temporarily for testing and dev ...

**Comment by ShreyasJejurkar** [comment]
Did you mean that I should improve the code base on Restyle_1 branch and then we can merge it together to master one?

**Comment by Dirkster99** [comment]
Yes, if thats possible it would make things much easier to sync us:

Projects in the **FSC** and **MLib** solution folder can be ignored since I am in the process of moving them into their respective repos and NuGets:
- https://github.com/Dirkster99/fsc
- https://github.com/Dirkster99/HistoryControlLib
- https://github.com/Dirkster99/MLib

**AvalonEdit** cam also be ignored unless you add critical bug fixes or features.

**Comment by ShreyasJejurkar** [comment]
OK. I will make code improvements to Restyle_1 branch from next time. My primary goal is to improve the code base and code quality over the time. And after that I will think about adding new feature or fixing bug.

**Comment by Dirkster99** [comment]
Sounds good to me - I am also bussy improving the code in terms of styles because its quit anoyingly chaotic so I am structuring things into seperate independant projects that have no idea of a specific theme or styling library just to use them with a styling/theming library in the end :-) This makes the components more useful and the project more flexible (I hope) ...but I should be done in a matter of weeks (after more than half a year phew) and don't see major coding changes - mostly just XAML stuff thats to be changed for me ... and then I'd like to add features of course :-)

**Pull request merged**
